### ISSUE TITLE
Make `git-clang-format` available too

### ISSUE THREAD

**Issue by mokafolio** [ssciwr/clang-format-wheel#108]
Is it possible to make `git-clang-format` available through this, too? Similar to a regular `clang-format` install? Thanks!

**Comment by dokempf** [comment]
We do so already, see here: https://github.com/ssciwr/clang-format-wheel/blob/main/pyproject.toml#L33 Is something about this not working for you?

**Comment by dokempf** [comment]
@mokafolio To me, it seems like that package definition just fails to expose the additional entrypoints here: https://github.com/mason-org/mason-registry/blob/main/packages/clang-format/package.yaml#L20 But I have no idea about mason.

**Comment by mokafolio** [comment]
@dokempf awesome, that was my hunch, too, thanks for taking a look!
