### ISSUE TITLE
Deployment Requirement Bugs

### ISSUE THREAD

**Issue by Skylion007** [ssciwr/clang-format-wheel#17]
We started trying to use the clang-format precommit hook on habitat-sim and came across a few bumps that could be easily fixed. First of all, on OSX unless you use a very recent version of pip (>=22) it will not use the wheel. This can be fixed by specifying `pip>=21` in the additional dependencies, but it may better to specify it in the setup.py itself, somewhere.

Also for the build from source, it really should include the pip version cmake so it doesn't try to use the old system's cmake as the version needed to build clang-format from source is also relatively recent (3.16).

**Comment by henryiii** [comment]
(On macOS, users should have a very recent version - older versions of pip don't even support macOS 11 correctly and can't download wheels at all)
