### ISSUE TITLE
Pip install does not work

### ISSUE THREAD

**Issue by nebbles** [ssciwr/clang-format-wheel#2]
Unable to pip install...

Python 3.8.0
pip 19.3.1
macOS 10.14.6

```
$ pip install clang-format
ERROR: Could not find a version that satisfies the requirement clang-format (from versions: none)
ERROR: No matching distribution found for clang-format
```

**Comment by mgevaert** [comment]
Thanks for the report.

Which operating system?

**Comment by nebbles** [comment]
macOS 10.14.6

**Comment by mgevaert** [comment]
Ah, thanks.  So far I've only built them for linux (as that's my primary platform).  I don't have a lot of experience supporting macOS, but I will see what I can do.

**Comment by nebbles** [comment]
Ah ok - I was a little unsure about what the package was providing. 

Could it be worth hosting/wrapping the statically built binaries from llvm? 
The specific use case was that I wanted the binaries installable through pip for consistency across developers and CI

**Comment by mgevaert** [comment]
Yup, I looked at what they were providing - just need to write some scripts to wrap it up.  Unfortunately, it looks like they don't build macOS versions of all their releases, only the 'major' ones.

The goal of this project is exactly what you want though - make CI easy so that the `clang-format` version can be consistently used.

**Comment by nebbles** [comment]
I may be able to lend a hand in places then 👍

**Comment by flovlad** [comment]
The same issue is seen on Windows:
Python 3.7.4
pip 20.0.2
OS Name:                   Microsoft Windows 10 Enterprise
OS Version:                10.0.18362 N/A Build 18362

`python -m pip search clang-format | grep clang-format
# clang-format (9.0.0)                 - pip installable clang-format
python -m pip install clang-format
# ERROR: Could not find a version that satisfies the requirement clang-format (from versions: none)
# ERROR: No matching distribution found for clang-format
`

I think the confusing thing is that pip shows you that there is an existing package, even if it is not available for your platform.

**Comment by g-karthik** [comment]
@mgevaert @nebbles any ideas what the fix for this is?

I get the following errors when running `pip install clang-format` on my Mac:

```
ERROR: Could not find a version that satisfies the requirement clang-format (from versions: none)
ERROR: No matching distribution found for clang-format
```

My python version is 3.6, pip version is 20.2.3 and Mac OS Mojave version 10.14.6.

**Comment by nebbles** [comment]
My workaround at the time which I have not readdressed was to download and commit the static binaries for mac (which I linked in an earlier message). 

I added these binaries to the git project that needed it under the `bin/clang-format/` directory, and then committed it to git. I use VSCode along with the other developers in my company and I linked the custom clang-format binaries path to the VSCode formatter using [the platform-settings extension](https://marketplace.visualstudio.com/items?itemName=runarsf.platform-settings) which allows us to use the binaries based on platform. 

Since updating clang-format is a very rare task we take on, just downloading and committing a recent version of the binary turned out to work quite well! Hope this helps

**Comment by POD666** [comment]
Almost the same as here:

> @mgevaert @nebbles any ideas what the fix for this is?
> 
> I get the following errors when running `pip install clang-format` on my Mac:
> 
> ```
> ERROR: Could not find a version that satisfies the requirement clang-format (from versions: none)
> ERROR: No matching distribution found for clang-format
> ```
> 
> My python version is 3.6, pip version is 20.2.3 and Mac OS Mojave version 10.14.6.

**Comment by nightlark** [comment]
The new clang-format 10.0.1, 11.0.1, 11.1.0, and 12.0.1 packages that have been released on PyPI now also include compiled macOS wheels with the `universal2` platform tag.

I'm not sure which exact version of `pip` support for the tag was added to (probably fairly recent), but maybe some people here with Macs can try them out on various systems.

**Comment by dokempf** [comment]
As @nightlark said, MacOS builds are now available for newer versions of clang-format. Please report any issues you might find with them.

**Comment by henryiii** [comment]
FYI, I tested this on Apple Silicon, and it works beautifully. :)
