### ISSUE TITLE
Is .clang-format supported?

### ISSUE THREAD

**Issue by robertbindar** [ssciwr/clang-format-wheel#29]
Hey! I'm trying to use the pre-commit clang-format mirror in CI https://github.com/pre-commit/mirrors-clang-format
which points to this wheel repository for further docs and info.

I can't see anywhere mentioned whether the CI precommit bot uses the `.clang-format` file from within a repository when pushing the changes commit. Is that supported, can it be configured somehow?

Thanks and sorry for opening an issue for this.

**Comment by robertbindar** [comment]
I've seen in the meantime the --style=file option passed to clang-format. That means `.clang-format` from root of repository will be used right?

Also, I've been trying for the past 3 hours to understand how to make the pre-commit bot run the clang-format hook only on the changed files from a PR, but I failed. If you know something about that, please let me know <3 It seems to me now that it's not possible.

**Comment by dokempf** [comment]
Yes, the format file from the root directory is taken. Not sure there is a way to do a partial application. I guess the motivation is to keep the history of a non-formatted code base clean?

**Comment by robertbindar** [comment]
That's exactly the motivation. I can't stop thinking though also about the waste of resources on pre-commit CI's side for running the hooks on the entire codebase every time.
In any case, thanks a lot for the help @dokempf, really appreciated and thanks for maintaining this nice piece of work.
