### ISSUE TITLE
clang-format 14.0.0 is available

### ISSUE THREAD

**Issue by martin-eder-zeiss** [ssciwr/clang-format-wheel#30]
Please create a release for clang-format 14.0.0

**Comment by henryiii** [comment]
Can be closed. ;)

**Comment by reupen** [comment]
It seems [this didn't make it to PyPI](https://pypi.org/project/clang-format/), is that known?

It looks like the step in the workflow was skipped for whatever reason: https://github.com/ssciwr/clang-format-wheel/runs/5823703004?check_suite_focus=true

Thanks

**Comment by dokempf** [comment]
I retriggered the workflow, so the version should be up in a few hours (takes a day or two for the mirror to pick it up). The upload step is accidentally skipped for release triggers. I will remove the release trigger entirely as I find it weird to do a release to find out whether things are still working as expected - should be the other way round.

**Comment by dokempf** [comment]
14.0.0 is now on PyPI.
