### ISSUE TITLE
How to format .h.in files

### ISSUE THREAD

**Issue by flagarde** [ssciwr/clang-format-wheel#33]
Hello, 
Thx for this nice pre-commit hook,

I have some header files that are generated by CMake. The input file has a .h.in extension and clang-format don't format it. How it is possible to add this extenssion to the hook ?

**Comment by HappyCerberus** [comment]
You can override the default file pattern on a hook using this option: https://pre-commit.com/#config-files

**Comment by flagarde** [comment]
Thank you for your fast response. I tried [types_or](https://pre-commit.com/#config-types_or) but i was not aware about files

**Comment by dokempf** [comment]
This should be solvable from within `.pre-commit-config.yaml` using above link. Closing.
