### ISSUE TITLE
Emulated builds exceed Github Actions free limit

### ISSUE THREAD

**Issue by dokempf** [ssciwr/clang-format-wheel#49]
Restructurings of the LLVM codebase in the 15.0.0 release drastically increased build times for `clang-format` again. This results in the 6 hour limit being hit for the emulated builds.

**Comment by renefritze** [comment]
I can host another runner in the VM for clang-tidy-wheel, once that's running smoothly.

**Comment by dokempf** [comment]
v16 changed the internal structure again, leading to emulated builds finishing within roughly two hours. Yeah!
