### ISSUE TITLE
Clang-format V15 Release

### ISSUE THREAD

**Issue by KipHamiltons** [ssciwr/clang-format-wheel#52]
G'day! Thanks for this project!

I noticed that the actions to deploy version 15 failed due to timing out the maximum action execution time. Are there any plans to get the execution time down or retry?

**Comment by dokempf** [comment]
There are plans to migrate to self-hosted runner once #32 is finished, but I might publish non-emulated builds earlier than that.

**Comment by KipHamiltons** [comment]
Thank you! Appreciate it!!
