### ISSUE TITLE
Support NixOS

### ISSUE THREAD

**Issue by Freed-Wu** [ssciwr/clang-format-wheel#71]
Comes from <https://github.com/pre-commit/mirrors-clang-format/issues/26>:

> This hook will download .cache/pre-commit/repon0nie2em/py_env-python3.10/lib/python3.10/site-packages/clang_format/data/bin/clang-format for me. However, My OS is NixOS, which doesn't respect HFS so it must patchelf every program. Inspired by ntkme/sass-embedded-host-ruby#116, I NIX_BINTOOLS=/nix/store/ngh5s155lcm1hwsakrfhla536x9g5v4z-binutils-wrapper-2.40 pre-commit run -a. It works for https://github.com/scop/pre-commit-shfmt, but cannot work for this hook. How to make it work?

**Comment by dokempf** [comment]
I browsed the internet a bit and there seems to be plenty of subtle issues with the `subprocess` module and NixOS. I have zero expertise in the latter, so I do not feel like I will be able to fix this. If somebody comes up with a fix that works for NixOS, I would consider integrating it though.

**Comment by Freed-Wu** [comment]
Inspired by <https://github.com/ntkme/sass-embedded-host-ruby/commit/985f4e2cade4c5cbe4e7cfb2a9d3289c6993bd94>, I try to `patchelf --set-interpreter $(cat $NIX_BINTOOLS/nix-support/dynamic-linker) /home/wzy/.cache/pre-commit/repon0nie2em/py_env-python3.10/lib/python3.10/site-packages/clang_format/data/bin/clang-format`. after `patchelf`, the result is

```sh
❯ ldd /home/wzy/.cache/pre-commit/repon0nie2em/py_env-python3.10/lib/python3.10/site-packages/clang_format/data/bin/clang-format
        linux-vdso.so.1 (0x00007ffdd1b7b000)
        libpthread.so.0 => /nix/store/8xk4yl1r3n6kbyn05qhan7nbag7npymx-glibc-2.35-224/lib/libpthread.so.0 (0x00007fd6e01c9000)
        librt.so.1 => /nix/store/8xk4yl1r3n6kbyn05qhan7nbag7npymx-glibc-2.35-224/lib/librt.so.1 (0x00007fd6e01c4000)
        libdl.so.2 => /nix/store/8xk4yl1r3n6kbyn05qhan7nbag7npymx-glibc-2.35-224/lib/libdl.so.2 (0x00007fd6e01bf000)
        libstdc++.so.6 => not found
        libm.so.6 => /nix/store/8xk4yl1r3n6kbyn05qhan7nbag7npymx-glibc-2.35-224/lib/libm.so.6 (0x00007fd6e00df000)
        libgcc_s.so.1 => /nix/store/8xk4yl1r3n6kbyn05qhan7nbag7npymx-glibc-2.35-224/lib/libgcc_s.so.1 (0x00007fd6e00c3000)
        libc.so.6 => /nix/store/8xk4yl1r3n6kbyn05qhan7nbag7npymx-glibc-2.35-224/lib/libc.so.6 (0x00007fd6dfe00000)
        /nix/store/8xk4yl1r3n6kbyn05qhan7nbag7npymx-glibc-2.35-224/lib/ld-linux-x86-64.so.2 => /nix/store/8xk4yl1r3n6kbyn05qhan7nbag7npymx-glibc-2.35-224/lib64/ld-linux-x86-64.so.2 (0x00007fd6e01d0000)
```

`libstdc++.so.6` is not found. Looks something I did wrong. Perhaps @ntkme know it?

**Comment by ntkme** [comment]
In my case the dart vm binary has everything expect glibc statically linked.

For glibc and its internal libraries, only `interpreter` path need to be set with patchelf.

However, for other libraries like `libstdc++`, you need to set `rpath` with patchelf. Or alternatively, you can set `LD_LIBRARY_PATH` environment variable at runtime.

**Comment by Freed-Wu** [comment]
I transport this question to nixos forum: <https://discourse.nixos.org/t/how-to-fix-some-c-c-programs-build-by-skbuild-for-nixos/27871>.

**Comment by Freed-Wu** [comment]
BTW, a temporary solution is

```shell
patchelf --set-rpath '$ORIGIN/../lib:'"$(nix eval --impure --expr '"${(import <nixpkgs> {}).stdenv.cc.cc.lib}/lib"' | jq -r .)" ~/.cache/pre-commit/repo*/py_env-python3.*/lib/python3.*/site-packages/clang_format/data/bin/clang-format
patchelf --set-interpreter $(nix eval --impure --expr '"${(import <nixpkgs> {}).glibc}/lib64/ld-linux-x86-64.so.2"'|jq -r .) ~/.cache/pre-commit/repo*/py_env-python3.*/lib/python3.*/site-packages/clang_format/data/bin/clang-format
```

**Comment by Freed-Wu** [comment]
I think I have known how to fix this issue:

In order to find the reason, I create a similar project
<https://github.com/Freed-Wu/astyle-wheel/> and provide a pre-commit-hooks.

```yaml
  - repo: https://github.com/Freed-Wu/astyle-wheel
    rev: "3.3"
    hooks:
      - id: astyle
```

It can work, I think pre-commit will download
<https://github.com/Freed-Wu/astyle-wheel> and build the project and install
it. Compile the C++ of astyle from source code in NixOS can get a correct binary program for NixOS.

However, for

```yaml
-   repo: https://github.com/pre-commit/mirrors-clang-format
    rev: ''  # Use the sha / tag you want to point at
    hooks:
    -   id: clang-format
```

pre-commit will download <https://github.com/pre-commit/mirrors-clang-format>
and build the python project and install it.
<https://github.com/ssciwr/clang-format-wheel> is a dependency of
<https://github.com/pre-commit/mirrors-clang-format>, so when we build mirrors-clang-format, it will `pip install clang-format-wheel`, and get a compiled binary program, not build it from source code. So the compiled binary program `clang-format` can not work for NixOS, which must `patchelf`. So the simplest solution to fix this issue is <https://github.com/ssciwr/clang-format-wheel> provides a `.pre-commit-hooks.yaml` like <https://github.com/Freed-Wu/astyle-wheel/> or <https://github.com/pre-commit/mirrors-clang-format>, and let user use it.

Although both `clang-format` and `astyle` are C formatters, I prefer `clang-format`. I hope this issue can be fixed. Thanks!

**Comment by Freed-Wu** [comment]
Hey, I've found the solution to run pre-commit hooks with compiled binary programs:

```sh
$ pre-commit run -a
clang-format..................................................................Failed
- hook id: clang-format
- exit code: 127

Could not start dynamically linked executable: /home/wzy/.cache/pre-commit/repo_x4pokos/py_env-python3.11/lib/python3.11/site-packages/clang_format/data/bin/clang-format
NixOS cannot run dynamically linked executables intended for generic
linux environments out of the box. For more information, see:
https://nix.dev/permalink/stub-ld
```

We have 2 methods:

## `patchelf` before `pre-commit run`

`patchelf.sh`:

```sh
#!/usr/bin/env bash
# patchelf all pre-commit hooks
tmp_dir="$HOME/.cache/pre-commit/repo"
if [ $# = 0 ]; then
    set -- \
        "${tmp_dir}"????????/rustenv-system/bin/* \
        "${tmp_dir}"????????/golangenv-system/bin/* \
        "${tmp_dir}"????????/py_env-python3.*/bin/* \
        "${tmp_dir}"????????/py_env-python3.*/lib/python3.*/site-packages/clang_format/data/bin/clang-format
fi
array=()
# remove non-dynamically linked programs
for bin; do
    ldd "$bin" &>/dev/null && array+=("$bin")
done
set -- "${array[@]}"
patchelf --set-interpreter "$(nix eval --impure --expr '"${(import <nixpkgs> {}).glibc}/lib64/ld-linux-x86-64.so.2"' | jq -r .)" "$@"
patchelf --set-rpath "$(nix eval --impure --expr '"${(import <nixpkgs> {}).stdenv.cc.cc.lib}/lib"' | jq -r .)" "$@"
```

Now, we can

```
$ patchelf.sh
$ pre-commit run -a clang-format
clang-format.............................................................Passed
```

### install nix-ld

Enable nix-ld:

`/etc/nixos/configuration.nix`:

```nix
programs.nix-ld.enable = true;
```

Config nix-ld:

`~/.bash_profile`:

```sh
export NIX_LD
eval "NIX_LD=$(nix eval --impure --expr '"${(import <nixpkgs> {}).glibc}/lib64/ld-linux-x86-64.so.2"')"
export NIX_LD_LIBRARY_PATH
eval "NIX_LD_LIBRARY_PATH=$(nix eval --impure --expr '"${(import <nixpkgs> {}).stdenv.cc.cc.lib}/lib"')"
```

Without patchelf, we can:

```sh
$ pre-commit run -a clang-format
clang-format.............................................................Passed
```

More details can be found <https://blog.thalheim.io/2022/12/31/nix-ld-a-clean-solution-for-issues-with-pre-compiled-executables-on-nixos/>
